stackrox/rhacs-observability-resources

resources/index.json

Some general improvements and an improved search and navigation of recent dashboards. See https://grafana.com/docs/grafana/next/whatsnew/whats-new-in-v9-4/ for full changelog.

update grafana version to 9.4.7

---

resources/grafana/rhacs-central-dashboard.yaml
resources/grafana/rhacs-cluster-overview-dashboard.yaml

It looks like a new rule has been added to the dashboard linter to check that variables are loaded on time change. Current PRs should be rebased to fix CI.

refresh variables on time change

---

resources/grafana/rhacs-central-slo-dashboard.yaml
resources/index.json

Add a Central SLO dashboard. Requires metrics defined in #76. Allows selection of individual or multiple Centrals. If multiple Centrals are selected, the averaged SLIs are shown.

add Central SLO dashboard

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/AWSRDSACUUtilization.yaml

* Remove the `avg_over_time` because AWS already aggregates metrics over a five minute interval.
* Switch the alert from `_maximum` to `_average` to be more resilient against temporary ACU spikes. 
* Add a filter based on the instance DB label. This is currently redundant, but just in case we ever export other ACU metrics in the future - for example total cluster ACU.

make acu alert more resilient against spikes

---

resources/grafana/rhacs-cluster-overview-dashboard.yaml

This PR includes some small changes to the cluster overview dashboard, in particular the cluster resource usage widget.
* Show cluster CPU and memory request and utilisation. The previous widget was misleading, because it is labelled as "Usage", but only showed the requests.
* Some minor quality of life fixes for when there are many Centrals.
- Sort tooltips.
- Show only single Central in tooltip for plots that include all Centrals.

show cpu/memory request and utilisation

---

resources/prometheus/prometheus-rules.yaml

In some cases the calculated SLI could become negative due to how Prometheus handles measurements on borders. This looks off in dashboard and is confusing, therefore clamp the values to make sure something like `-0.0001` just becomes `0`.

clamp extended average between 0 and 1

---

resources/grafana/rhacs-central-dashboard.yaml
resources/grafana/rhacs-central-slo-dashboard.yaml
resources/grafana/rhacs-cluster-overview-dashboard.yaml

Filter out instances created by the probe organisation (`rhacs_org_id!=\"16536854\"`) in the dashboard variables. The reason is that the probes creates ~100 instances a day, which clutter the dashboards.

ignore probe instances in dashboards

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/RHACSFleetshardSyncCentralReconcilePaused.yaml

Alert when an ACS instance has had the `pause-reconcile` annotation for more than 2 days.
See also https://github.com/stackrox/acs-fleet-manager/pull/1065

ROX-15234: Alert when instance has pause-reconcile for more than 2 days

---

resources/mixins/kubernetes/generated/alerts.yml
resources/mixins/kubernetes/jsonnetfile.lock.json
resources/mixins/kubernetes/mixin.libsonnet
resources/prometheus/kubernetes-mixin-alerts.yaml

Set `namespaceSelector: 'namespace=~"rhacs-.*|acscs-.*"'` in jsonnet `_config`, to effectively have alerts only on ACS workloads.
See [the related thread](https://redhat-internal.slack.com/archives/CCX9DB894/p1687381918802879?thread_ts=1687297268.055499&cid=CCX9DB894) for the context on why SRE supports this.

Generate kube-state alarms only for RHACS namespace

---

resources/grafana/rhacs-cluster-overview-dashboard.yaml

Some improvements to the cluster dashboard:
* Add AZ resource widgets
* These replace the previous cluster resources widget.
* Usage is now limited to actual worker nodes.
* Usage is broken down by availability zone.
* Remove useless Central volume widget.
* No longer used after postgres migration. Volumes for all Centrals on prod are `<< 1%` usage, so the widget did not show relevant info.
* Add secured cluster widget.
* Just shows the number of secured clusters in addition to cores and nodes.

cluster dashboard improvements

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/RHACSCentralSLISLO.yaml

The issue addressed here is that with the latest haproxy metrics changes, we are running into scenarios where metrics are undefined. In these cases we provide defaults, which however do not have the correct `rhacs_*` labels.
To fix this issue, we always add `rhacs_instance_id` to `central:sli:pod_ready`. This helps us to make sure that `central:sli:error_rate` has either all `rhacs_*` labels or at least `rhacs_instance_id` attached. This should prevent Prometheus from dropping metric series or messing up `central:sli:availability`.
To summarize, the following scenarios may occur:
* `>= 1` pods available, but no incoming requests
* all error rate metrics are undefined.
* `central:sli:error_rate` defaults to `rox_central_postgres_connected=1`.
* `rhacs_instance_id`, `rhacs_org_id`, …

fix labels in SLI metrics

---

resources/grafana/mixins/kubernetes/k8s-resources-cluster.yaml
resources/grafana/mixins/kubernetes/k8s-resources-namespace.yaml
resources/grafana/mixins/kubernetes/k8s-resources-node.yaml
resources/grafana/mixins/kubernetes/k8s-resources-pod.yaml
resources/grafana/mixins/kubernetes/k8s-resources-workload.yaml
resources/grafana/mixins/kubernetes/k8s-resources-workloads-namespace.yaml
resources/mixins/kubernetes/generated/alerts.yml
resources/mixins/kubernetes/generated/dashboards/k8s-resources-cluster.json
resources/mixins/kubernetes/generated/dashboards/k8s-resources-namespace.json
resources/mixins/kubernetes/generated/dashboards/k8s-resources-node.json
resources/mixins/kubernetes/generated/dashboards/k8s-resources-pod.json
resources/mixins/kubernetes/generated/dashboards/k8s-resources-workload.json
resources/mixins/kubernetes/generated/dashboards/k8s-resources-workloads-namespace.json
resources/mixins/kubernetes/jsonnetfile.lock.json
resources/mixins/kubernetes/mixin.libsonnet
resources/prometheus/kubernetes-mixin-alerts.yaml

Increasing the area of ignored alerts due to some unwanted pages for the `openshift-marketplace` namespace (in this case the `community-operator` pod).
_Note for reviewers: unsure why there are so many changes within the dashboard after running `make generate`._

Ignore kube-mixin alerts for openshift-marketplace

---

Makefile
resources/mixins/kubernetes/Makefile
resources/mixins/kubernetes/README.md

Separate `generate` and `update` from each other, such that one can regenerate the mixins without also having to update their revision.

fix(makefile): separate `generate` and `update` commands

---

resources/mixins/kubernetes/generated/alerts.yml
resources/mixins/kubernetes/jsonnetfile.lock.json
resources/mixins/kubernetes/mixin.libsonnet
resources/prometheus/kubernetes-mixin-alerts.yaml

The changes in #125 are not sufficient to suppress CPU throttling alerts because the mixin uses a separate `cpuThrottlingSelector` for the CPU throttling alerts. This change now ignores CPU throttling explicitly for all `openshift-.*` namespaces.

fix(alerts): ignore CPU throttling for `openshift-*`

---

.pre-commit-config.yaml

The old versions seem to break the pre-commit hook on master, see https://github.com/stackrox/rhacs-observability-resources/actions/runs/5861091004/job/15890846319. Updating to the latest versions seems to fix it.

chore(pre-commit): update deps

---

resources/mixins/kubernetes/generated/alerts.yml
resources/mixins/kubernetes/mixin.libsonnet
resources/prometheus/kubernetes-mixin-alerts.yaml

Fix a typo in the selector string - missing a `"` to terminate correctly.
See #133 for fixing the pre-commit hook in CI.

fix(mixins): typo in cpu throttle selector

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/RHACSCentralSLISLO.yaml

With the current metrics definition we observed that in rare cases `central:sli:error_rate > 1` for short periods. This can happen if Prometheus reports inconsistent values for incoming traffic, e.g. when 2xx requests are higher than total requests. This is caused by the disparity between processed and in-flight requests. As a result of this bug, the error budget exhaustion may appear smaller than it is.
This PR addresses this issue by:
* refactoring the definition by extracting recording rules. This is helpful when investigating error rates.
* use only gRPC requests that already have terminated without considering in-flight requests.
* adding a `clamp` just in case.

fix(sli): clamp error rate at 1

---

resources/prometheus/prometheus-rules.yaml

While testing the metrics on stage, this felt like a more appropriate name since it's the ratio of available / total requests.

refactor(metrics): rename error_rate -> success_rate

---

resources/prometheus/prometheus-rules.yaml

Small refactoring of the promQL query to make it more promQL idiomatic.
* `sum` -> `max`: Both are equivalent here because we are summing/maxing over a single value. However `max` shows the intention more clearly imo.
* `floor` -> `> bool`: This does the same thing, but `> bool` is the promQL native way to perform the floor.

refactor(metrics): use prom bool comparison

---

resources/grafana/rhacs-central.json

This PR restructures widgets in the DB metrics row and adds legend panel for the "Postgres object count" bootstrapped with explanation for the pattern of `network_flows_v2`.
JSON's version and schema version are bumped, other seemingly unrelated changes are manually removed from the exported JSON before the PR has been prepared.

Add legend panel in DB metrics row

---

resources/prometheus/federation-config.yaml

Central integrates now with OpenShift platform prometheus. As such, we need to exclude these metrics from the platform metrics federation to prevent double counting.

no federation of central platform metrics

---

resources/prometheus/prometheus-rules.yaml

This is a workaround to the SLO issue observed in https://issues.redhat.com/browse/ROX-19887.
In short, due to flawed ordering of gRPC interceptors in Central, client errors were counted as `Unknown` gRPC codes in Prometheus metrics. To protect our SLO metrics from ballooning out of control, we temporarily not count `Unknown` errors as server errors.
This is to be reverted again once https://github.com/stackrox/stackrox/pull/7942 is released and deployed to production. See https://issues.redhat.com/browse/ROX-19917 for the task to do exactly that.

fix(sli): allow `Unknown` status code in SLI error rate

---

.github/workflows/slack.yaml

Post a notification to Slack about any push to production, so that release engineers are aware.
Test workflow run: https://github.com/stackrox/test-gh-actions/actions/runs/6691295752
Resulting message in the test channel: https://redhat-internal.slack.com/archives/C03KSV3N6N8/p1698660800307679

ROX-20385: Slack notification workflow

---

resources/index.json

Includes base image upgrades and CVE fixes. I skimmed the breaking changes introduced with 10.x (https://grafana.com/docs/grafana/latest/breaking-changes/breaking-changes-v10-0/) and did not notice anything that would affect us. So I think it's safe to merge and test on integration env.

chore: bump grafana version to 10.2.0

---

resources/grafana/generated/dashboards/rhacs-cluster-resource-adjustment-configmap.yaml
resources/grafana/generated/dashboards/rhacs-cluster-resource-adjustment-dashboard.yaml
resources/grafana/templates/dashboards/rhacs-cluster-resource-adjustment-configmap.yaml
resources/grafana/templates/dashboards/rhacs-cluster-resource-adjustment-dashboard.yaml

Accidentally mixed up the `ConfigMap` and `GrafanaDashboard` resources in #158.

fix cluster resource template file names

---

.pre-commit-config.yaml
scripts/run-make-generate.sh

Run `make generate` as part of the pre-commit hook. It should fail if there is anything modified, i.e. if there was anything generated.

feat: add `make generate` to pre-commit hook

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/RHACSOperatorMemoryUtilizationHigh.yaml

I changed the alert to be goruped by (namespace, workload, container) instead of (namespace, workload) because we might approach OOM in 1 container and not in the other, and the previous alert would not have caught it

ROX-20792: Add critical alert for operator OOM

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/RHACSTenantWorkloadMemoryUtilizationHigh.yaml

Adding alerts for tenant containers that are about to oom

ROX-21046: Alerts for tenant nearing OOM

---

resources/grafana/generated/dashboards/rhacs-central-slo-configmap.yaml
resources/grafana/generated/dashboards/rhacs-central-slo-dashboard.yaml
resources/grafana/sources/rhacs-central-slo.json

Make the SLI graphs more readable by showing a proxy that renders better in Grafana. The problem right now is that Grafana swallows up spikes and instead renders a flat line. The proxy metric works by extending the "downtime" interval via `changes(...[1h])`, such that Grafana has an easier way rendering it. The downside is that downtimes may appear longer than they were - however, the overall percentages (9' notation) are still exact.
Before:
After:
The dashboard can be viewed temporarily under https://grafana-route-rhacs-observability.apps.acs-prod-dp-01.pnz3.p1.openshiftapps.com/d/a3d89363-95c2-470f-82d8-cd9c62fe3840/rhacs-dataplane-central-slos-copy?orgId=1.

chore: make SLI graphs more readable

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/RHACSTenantWorkloadMemoryUtilizationHigh.yaml

We have seen that the tenant memory alerts are too noisy in their current state. See https://redhat-internal.slack.com/archives/C0313JYKH8W/p1702483155046459 for a discussion.
Tighten the alerts by:
* constrain to `central` containers.
* increase the thresholds.

chore: tighten tenant memory alerts

---

resources/grafana/mixins/kubernetes/apiserver.yaml
resources/grafana/mixins/kubernetes/cluster-total.yaml
resources/grafana/mixins/kubernetes/controller-manager.yaml
resources/grafana/mixins/kubernetes/k8s-resources-cluster.yaml
resources/grafana/mixins/kubernetes/k8s-resources-namespace.yaml
resources/grafana/mixins/kubernetes/k8s-resources-node.yaml
resources/grafana/mixins/kubernetes/k8s-resources-pod.yaml
resources/grafana/mixins/kubernetes/k8s-resources-workload.yaml
resources/grafana/mixins/kubernetes/k8s-resources-workloads-namespace.yaml
resources/grafana/mixins/kubernetes/kubelet.yaml
resources/grafana/mixins/kubernetes/namespace-by-pod.yaml
resources/grafana/mixins/kubernetes/namespace-by-workload.yaml
resources/grafana/mixins/kubernetes/persistentvolumesusage.yaml
resources/grafana/mixins/kubernetes/pod-total.yaml
resources/grafana/mixins/kubernetes/proxy.yaml
resources/grafana/mixins/kubernetes/scheduler.yaml
resources/grafana/mixins/kubernetes/workload-total.yaml
resources/mixins/kubernetes/scripts/generate-dashboards.sh

Main change in `resources/mixins/kubernetes/scripts/generate-dashboards.sh`
There is an inconsistency in how linux and macos generates k8s mixin grafana dashboards. TBH, I am not sure what cause the problem but there is json -> yaml -> json transformation and if eliminate it then it works just fine.
This PR should make it cross OS and also it inserts json body as-is without changing order nor modifications
This should fix #184 CI pipeline

Change yq json inserting to make it the same for linux and macos

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/RHACSOperatorMemoryUtilizationHigh.yaml

See slack thread where this was discussed.
* It's a bit noisy a the current level
* 60% utilization is not a reason for concern
* the current memory usage seems sane given the size of `Secrets` in the prod cluster, which the operator must all cache

Bump threshold for warning on operator memory usage from 60% to 70%.

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/AWSSESQuota.yaml

ROX-21739: SES Monitoring

---

resources/grafana/generated/dashboards/rhacs-cluster-overview-configmap.yaml
resources/grafana/generated/dashboards/rhacs-cluster-overview-dashboard.yaml
resources/grafana/sources/rhacs-cluster-overview.json

3 commits:
1. JSON indentation;
2. New column;
3. `make generate`.

feat: add `rhacs_expired_at` to centrals overview panel

---

resources/grafana/generated/dashboards/rhacs-cluster-overview-configmap.yaml
resources/grafana/generated/dashboards/rhacs-cluster-overview-dashboard.yaml
resources/grafana/sources/rhacs-cluster-overview.json

More improvements to the cluster overview dashboard:
* use `inner` instead of `outer` joins in the central/scanner tables. This removes the spurious probe instances.
* add `Organization ID` columns.
* some minor cosmetic adjustments of the columns widths to try to fit one more column.
Link to test dashboard: https://grafana-route-rhacs-observability.apps.acs-prod-dp-01.pnz3.p1.openshiftapps.com/d/cb108eaa-ab11-4016-b1c0-46e063f41b1d/stehessel-rhacs-dataplane-cluster-metrics?orgId=1 
Screenshot:

chore: remove probe instances from table

---

.github/workflows/sync-prod-from-stage.yaml
.github/workflows/sync-stage-from-master.yaml

Prevent merge conflicts due to squash commits when syncing `master` -> `stage` -> `production`.

chore: add auto-merge in sync

---

resources/grafana/generated/dashboards/rhacs-cluster-overview-configmap.yaml
resources/grafana/generated/dashboards/rhacs-cluster-overview-dashboard.yaml
resources/grafana/sources/rhacs-cluster-overview.json
resources/prometheus/federation-config.yaml

- Add ScannerV4 components to Scanner Overview Table (Located at `Dashboards -> rhacs-observability -> RHACS Dataplane - Cluster Metrics`)
- Improve correctness for memory calculation
- Drop Network received/transmitted because it is already displayed on the same page on time series manner
- Add ACS Version
- Use selected range for CPU rate calculation
- Mark deleted instances which had metrics in the selected time range
- Other minor tweaks
Example of applied changes on test environment:

ROX-22677: Add ScannerV4 components to Scanner Overview table

---

.github/workflows/automerge.yaml
.github/workflows/sync-prod-from-stage.yaml
.github/workflows/sync-stage-from-master.yaml

The `PULL_REQUEST_AUTO_MERGE_METHOD` option on the sync action did not seem to work. It did not enable `auto-merge` as expected. Instead, introduce a dedicated automerge action.

fix: automerge action

---

resources/prometheus/federation-config.yaml
resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/ClusterAutoscalerNotSafeToScale.yaml
resources/prometheus/unit_tests/ClusterAutoscalerUnableToScaleCPULimitReached.yaml
resources/prometheus/unit_tests/ClusterAutoscalerUnableToScaleMemoryLimitReached.yaml
resources/prometheus/unit_tests/ClusterAutoscalerUnschedulablePods.yaml
resources/prometheus/unit_tests/WorkerNodesCPUQuotaOverCommit.yaml
resources/prometheus/unit_tests/WorkerNodesMemoryQuotaOverCommit.yaml

This PR adds alerts related to cluster autoscaler behavior, and it removes alerts related to previous manual scaling.
Alerts are taken from default Openshift operator alerts: https://github.com/openshift/cluster-autoscaler-operator/blob/287595b0ee37b893c02d51d3a461ba118b90c3dc/pkg/controller/clusterautoscaler/monitoring.go#L153
Additional documentation related to alerts can be found here: https://github.com/openshift/cluster-autoscaler-operator/blob/287595b0ee37b893c02d51d3a461ba118b90c3dc/docs/user/alerts.md
They have different levels.

ROX-23673: Add alerts for cluster autoscaler

---

resources/grafana/generated/dashboards/rhacs-autoscaler-configmap.yaml
resources/grafana/generated/dashboards/rhacs-autoscaler-dashboard.yaml
resources/grafana/sources/rhacs-autoscaler.json
resources/grafana/templates/dashboards/rhacs-autoscaler-configmap.yaml
resources/grafana/templates/dashboards/rhacs-autoscaler-dashboard.yaml
resources/index.json
resources/prometheus/federation-config.yaml

A new Grafana dashboard for the Kubernetes autoscaler. The dashboard code is re-used from https://grafana.com/grafana/dashboards/12623-cluster-autoscaler-stats/. You can see the new dashboard here https://grafana-route-rhacs-observability.apps.acs-prod-dp-01.pnz3.p1.openshiftapps.com/d/bf73f356-19e7-4b83-9f5c-f63cd2e647d5/kubernetes-cluster-autoscaler-via-prometheus?orgId=1, although not all required metrics are federated yet (see changes to `federation-config.yaml`).

feat(dashboards): add autoscaler dashboard

---

resources/index.json

routine Grafana update, see changelog for changes https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v10-4/. The next version will be a major version bump to `11.x`.

chore(deps): bump grafana to 10.4.0

---

resources/grafana/generated/dashboards/rhacs-cluster-overview-configmap.yaml
resources/grafana/generated/dashboards/rhacs-cluster-overview-dashboard.yaml
resources/grafana/sources/rhacs-cluster-overview.json

Not sure what happened in #231 and #221. Somehow the widget was assigned to the wrong section.
Now it should be correct hopefully.
broken: https://grafana-route-rhacs-observability.apps.acs-int-us-01.isbr.p1.openshiftapps.com/d/4032f3c17643119901e107a0a1786d5b9e4c9565/rhacs-dataplane-cluster-metrics?orgId=1
fixed: https://grafana-route-rhacs-observability.apps.acs-int-us-01.isbr.p1.openshiftapps.com/d/foobar/rhacs-dataplane-cluster-metrics?orgId=1

fix: cluster overview widget alignment

---

.github/workflows/sync-prod-from-stage.yaml
.github/workflows/sync-stage-from-master.yaml

It seems like the action actually wants the labels array to be passed as a string https://github.com/TreTuna/sync-branches/blob/main/action.yml#L36-L39.

fix: pass labels array as string

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/ClusterAuditSELinuxViolations.yaml

This is part of https://issues.redhat.com/browse/ROX-22148.
1. SOP is currently under review.
2. The ACSCS release which prevents the Scanner violations is scheduled for today.
Could we do the review now and then merge when (1) and (2) are completed?

ROX-23900: Add prometheus alert for SELinux violations

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/ClusterAuditNetworkPolicyViolations.yaml

This is part of https://issues.redhat.com/browse/ROX-22148.
The SOP is ~~currently under review~~ merged.
Currently we don't expect to have a zero-baseline for network policy violations until GA, hence this PR aims to allow the current non-zero behaviour.
The behaviour we currently observe is related to "probe namespaces", which are short-lived and cause -- for a "short" period of time -- a "small" amount of violations. I have decided to implement to two different alerting triggers:
1. One, which triggers directly in case the violations cross a certain threshold (per minute), currently set to 15 violations per minute.
2. One, which triggers if any positive amount of violations has been observed for longer than 10 minutes.
Would be great if we could do the review in parallel to the other …

ROX-23558: Add Network Policy alert

---

resources/grafana/generated/dashboards/rhacs-central-slo-configmap.yaml
resources/grafana/generated/dashboards/rhacs-central-slo-dashboard.yaml
resources/grafana/generated/dashboards/rhacs-cluster-overview-configmap.yaml
resources/grafana/generated/dashboards/rhacs-cluster-overview-dashboard.yaml
resources/grafana/sources/rhacs-central-slo.json
resources/grafana/sources/rhacs-cluster-overview.json

Fixing the missing annotations in ACS-CS dashboards. Switching to `count_over_time`
https://grafana-route-rhacs-observability.apps.acs-int-us-01.isbr.p1.openshiftapps.com/d/4032f3c17643119901e107a0a1786d5b9e4c9565/rhacs-dataplane-cluster-metrics?orgId=1&from=now-90d&to=now

ROX-24822: Fix acs-cs annotations

---

.github/workflows/automerge.yaml
.github/workflows/sync-prod-from-stage.yaml
.github/workflows/sync-stage-from-master.yaml

The `automerge` workflow currently does not work. This PR addresses the following problems with it:
* the current sync action is outdated and doesn't work properly (lables are not being set). I've updated to a maintained fork.
* the author filter in the automerge workflow is missing the `[bot]` suffix.

fix: branch sync workflow

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/RHACSCentralSLISLO.yaml

A new slow burn alert that triggers when the error budget exhaustion has increased by more than 10% over the last week. This is meant to supplement the other slow burn alerts that trigger at absolute exhaustion thresholds (50%, 70%, 90%).

feat(alerts): add weekly exhaustion alert

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/ClusterAuditNetworkPolicyViolations.yaml

The alert is triggering to often currently.
This PR:
* Removes one trigger entirely.
* Increases the threshold for the second remaining trigger.
* 
Here's a graph showing the amount of violations we currently have to treat as being normal:

Increase alerting threshold for networt policy violations

---

.github/workflows/automerge.yaml

Ok this broke the automerge action again :( (see https://github.com/stackrox/rhacs-observability-resources/pull/263). Let's just revert it and let it be as it was.
Reverts stackrox/rhacs-observability-resources#262

Revert "chore: add more automerge options"

---

resources/grafana/generated/dashboards/rhacs-central.yaml
resources/grafana/sources/rhacs-central.json

For investigation purposes it might be important to obtain an holistic view of container restarts within tenant namespaces, not only for central and scanner.

Add missing containers to "Container Restarts" graph

---

resources/prometheus/prometheus-rules.yaml

I've tested this alert as part of https://issues.redhat.com/browse/ROX-21873 by blocking DB ingress via AWS security groups.
It took 35 minutes for this alert to appear in alertmanager. This is because we're working with the AVG metric in this alert and have a wait time of 20 minutes defined. Since a broken DB connection means a critical state for the entire system I think we should alert earlier on this.
Looking at the metrics for longer running tenants it seems to make sense to continue using the AVG because on central rollouts this metric might be down for some time. So instead of increasing the threshold I reduced the wait time to 10 minutes.

ROX-21873: increase sensitivity on alert for tenant db connections

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/RHACSEmailsenderContainerDown.yaml
resources/prometheus/unit_tests/RHACSEmailsenderContainerFrequentlyRestarting.yaml
resources/prometheus/unit_tests/RHACSEmailsenderScrapeFailed.yaml.yaml
resources/prometheus/unit_tests/RHACSEmailsenderSendErrors.yaml
resources/prometheus/unit_tests/RHACSEmailsenderThrottledSend.yaml

Add essential Email Sender alert.
All alerts are marked as warning on purpose. it's better to soak those alerts as warnings
There is an open MR for Email Sender SOPs: https://gitlab.cee.redhat.com/stackrox/acs-cloud-service/runbooks/-/merge_requests/114

ROX-25003: Add emailsender alerts

---

resources/prometheus/prometheus-rules.yaml

Reverts stackrox/rhacs-observability-resources#271
The alert has been firing for every probe instance since the change. The 10 mins seem to not be enough to take the provisioning time into account.
We need to revert before this is shipped to prod.

Revert "ROX-21873: increase sensitivity on alert for tenant db connections"

---

.github/workflows/main.yml

`pre-commit` CI step [fails](https://github.com/stackrox/rhacs-observability-resources/actions/runs/11294068645/job/31413669648?pr=281) with:
```
Run pre-commit/action@v3.0.1
Run python -m pip install pre-commit
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
```
GH actions uses `ubuntu-latest` and GH recently started to [migrate ubuntu version](https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/). The new ubuntu version comes with new python and pip. The new pip fails to install system wide packages by default to follow[ PEP-668](https://peps.python.org/pep-0668/). Technically it should not be an …

FIX: Fix pre-commit CI

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/RHACSTenantWorkloadMemoryUtilizationHigh.yaml

`RHACSTenantWorkloadMemoryUtilizationHigh` is a noisy alert and sometimes it resolves itself after short period of time. More details in the [ticket ROX-26472](https://issues.redhat.com/browse/ROX-26472)

ROX-26472: Increase RHACSTenantWorkloadMemoryUtilizationHigh eval time to 30 minutes

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/RHACSTenantWorkloadMemoryUtilizationHigh.yaml

As a result of the Running the Service meeting on 29.10.2024, we decided to increase the tenant workload memory alert threshold to 90% to reduce the VPA's noisiness.

Increase tenant workload memory alert threshold to 90%

---

resources/grafana/generated/dashboards/rhacs-cluster-overview.yaml
resources/grafana/sources/rhacs-cluster-overview.json

There are 2 steps prior to this PR:
First step was to Implement monitoring for certificate expiration, tracking and managing of digital certificates expiration dates. Certificate Monitoring PR: [ROX-21530-certificate-monitoring](https://github.com/stackrox/acs-fleet-manager/tree/ROX-21530-certificate-monitoring) , extracts timestamps from certificates and exposes metrics to Prometheus.
The second step was the Alerting part. Certificate Alerting PR: [ROX-21530-certificate-alerting](https://github.com/stackrox/rhacs-observability-resources/tree/ROX-21530-certificate-alerting) depends on the monitoring phase for timestamp exposing and extraction. So, External dependencies: adding/extracting the metrics : [ROX-21530-certificate-monitoring](https://github.com/stackrox/acs-fleet-manager/tree/ROX …

ROX-21530: Cert Expiry Dashboard

---

resources/grafana/generated/dashboards/rhacs-cluster-overview.yaml
resources/grafana/sources/rhacs-cluster-overview.json

Version Control got updated--> double instances and 'rox_central_info' is causing both to be shown, updated query expression to account for this.

ROX-21530: Update Cert Expiry Dashboard

---

resources/prometheus/prometheus-rules.yaml
scripts/generate-federate-match.sh

Add `InfoInhibitor` rule to inhibit info alerts unless other alerts fire in the same namespace

ROX-27298: Add InfoInhibitor to the prometheus rules

---

resources/grafana/generated/dashboards/rhacs-central.yaml
resources/grafana/sources/rhacs-central.json

- Set GraphQL vectors to 0 if data is not available
- Fix the issue when GraphQL dashboards are not rendered. The problem was related to `$__interval`. This variable is calculated by this formula `Time range / Max data points`. Grafana `sets Max data points` automatically by default but it depends on selected time range and probably number of returned points. As a result `$__interval` could be super small so no data is shown. The issue was fixed by setting minimum value for `$__interval` and set `Max data points` to static value.
- Simplify a little an existing `Query Duration Percentiles` and add a separate heatmap which shows details about GraphQL queries distribution
Result:

Fix Central GraphQL dashboard and add duration heatmap

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/RHACSFleetshardSyncCentralCountHealthMismatch.yaml
resources/prometheus/unit_tests/RHACSFleetshardSyncCentralCountPodMismatch.yaml

Add 2 alerts that may indicate that Central SLO metrics are undefined:
1. Compare total central count and the number of central pods;
2. Compare total central count and the number of central healthcheck probes.

ROX-16860: Cover undefined availability metrics in Central SLOs

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/SecuredClusterDrop.yaml

The alert definition for SC drops is wrong it should be `< 0.5` as opposed to `< 50` for the expression.
additionally I changed the severity to warning so we can monitor and tune this for some time before making it critical which causes paging via PagerDuty.

fix: alert for SC drop and make it a warning for now

---

resources/prometheus/prometheus-rules.yaml
resources/prometheus/unit_tests/SecuredClusterDrop.yaml

Add the URL of the SoP for secured cluster drop alerts.

ROX-28713: add SOP URL for secured cluster drop alerts

---

resources/prometheus/prometheus-rules.yaml

The error budget alerting is producing a lot of noise in case of incidents, because it fires for 28 days after the incident though no tenants are down anymore.
This PR changes the budget alert to only fire if central availability was 0 in the last hour.

ROX-29371: change error budget alerting for less noise

---

resources/prometheus/prometheus-rules.yaml

We're going to disable scanner-db high memory alerting, because we have metrics reporting issues.
See tickets and ticket comments for reasoning:
- [ROX-30068](https://issues.redhat.com/browse/ROX-30068)
- [ROX-30025](https://issues.redhat.com/browse/ROX-30025)
With this change we won't get alerted for high memory usage anymore, but we still have alerts for OOMs which will let us know if scaling is required.

ROX-30068: disable memory utilization alerts for scanner-db
